name: sleep then echo

on:
  push:

jobs:
  sleep-echo:
    runs-on: ubuntu-latest
    steps:
      - name: sleep then echo
        run: |
          echo "Sleeping for 10..."
          sleep 10
          echo "Time to wake up!"
          exit 0